### ISSUE TITLE
For loops in mTree

### ISSUE THREAD

**Issue by peteribanks** [gmucsn/mTree#10]
Hey Steve, 

Thank you for answering all of our questions and addressing all of our issues. Me and Jeffery have precipitantly been running into the same issue with for loops in mTree. We are facing the same problem at a different point that we faced the Friday before we left for break. namely the issue of for loops over writing the messages before they can be acted upon by their receiver. As an example if there is one agent with a single heuristic who will use 12 sets of boxes, a for loop is needed to run through all 12 boxes in the given heuristic. unfortunately what appears to be happening is that only box 12 is used 12 times, the other 11 boxes are over written before they can be used by the agent. Since we do not have a deep understanding of the way messages are handled or stored its unclear where exactly this error is stemming from other than the fact that only the last message is used. If you have any solutions or insights that would be great. 

Peter

**Comment by peteribanks** [comment]
Here is the code we are using. when the for loop inside of the environment that sends boxes to the institution has a break in it the system works. but when that break is removed, the code stops behaving as we would expect. We have tried a number of fixes so if you have any questions about things that we have tried let us know.
[non_crashing_version_of_v2.zip](https://github.com/gmucsn/mTree/files/2180714/non_crashing_version_of_v2.zip)

Peter

**Comment by peteribanks** [comment]
also as a note the for loop in the runner works expected. Where it can run through multiple environments without a problem. 

Peter

**Comment by skunath** [comment]
can you make the code available in a repo or something more readily commentable?

**Comment by peteribanks** [comment]
How/where, do you want me to upload a file to the main mTree branch I don't want to ruin anything.

**Comment by skunath** [comment]
can you create a new repository for your experiment that is private to gmucsn, post your code there, and then let me know?
