### ISSUE TITLE
mTree

### ISSUE THREAD

**Issue by peteribanks** [gmucsn/mTree#11]
Hey Steve, 

I know on Friday you described message handling to be a que, me and jeffery were wondering if it was possible to change it so new messages where added to the front of the que rather than the back this might solve the problem that we are facing.

**Comment by skunath** [comment]
That's not really possible as it would break a bunch of other things. It'll be important to look through your code as my suspicion would be that things should just work. 
I'll check out your repo and try to get back to you soon.
