### ISSUE TITLE
mTree message.get_sender() not working

### ISSUE THREAD

**Issue by rfraser4** [gmucsn/mTree#27]
There's an issue where the setting the sender does not seem to work. In the debug it's printing the else and the statement before.

![steve issue](https://user-images.githubusercontent.com/47042204/61300165-74ab2780-a7af-11e9-98aa-bbbbf03bca2b.PNG)

**Comment by skunath** [comment]
Is this not working or not getting the value you want? The sender should be an address which will look somewhat odd.

**Comment by rfraser4** [comment]
So it seems like it's not actually sending an address but something more like an object

**Comment by rfraser4** [comment]
![steve issue 4](https://user-images.githubusercontent.com/47042204/61382664-324f1c80-a87b-11e9-817b-7f7a6a83e0f2.PNG)
![steve issue 5](https://user-images.githubusercontent.com/47042204/61382670-354a0d00-a87b-11e9-9e1c-4c4a7e3c9430.PNG)

Here's the issue. It actually doesn't seem to be sending the address but an object. The output with the $$ is from get sender and that with ## is the actual address of the lender and borrower.

**Comment by skunath** [comment]
Which one are you referring to in your output?

The actorAddr is the address. The <Agent: ... > is just a string
representation of the actor object.

Is your code in the repo up to date?

**Comment by rfraser4** [comment]
The message.get_sender() gives us the string representation of the Agent address, not the address (which we can get from the institution_state['lender'] and borrower).

Yes the code should be up to date.

**Comment by skunath** [comment]
Does it give you a string, or are you seeing a string when you print? That
is, it could be handing the object but whenever you do a print on it, it
will use the __repr__ method to generate a representation in string format.

**Comment by rfraser4** [comment]
![steve issue 6](https://user-images.githubusercontent.com/47042204/61384936-907dfe80-a87f-11e9-96a4-12b37466e880.PNG)

Sorry it's an object, pictured here. Basically we're getting the object from get_sender() but we can't get it's address to compare to our own index of actors.

**Comment by skunath** [comment]
can you post the link to the file that the code for this is in?

**Comment by rfraser4** [comment]
https://github.com/gmucsn/REU_2019_Simulations/blob/fraserdevbranch/mes/collateral_game_institution.py
Sure, here it is, line 155-160.

**Comment by skunath** [comment]
Ok. Try to access this property:
message.get_sender().myAddress

I think the system is allowing for object passing and not forcing the
addresses to be used. This would be something with the underlying actor
system implementation we are using at present.

**Comment by rfraser4** [comment]
That appears to have done it!
