### ISSUE TITLE
question regarding module importing 

### ISSUE THREAD

**Issue by maggielehr** [gmucsn/mTree#3]
I am looking at the import statements on environment, institution, and agent and there appears to be some discrepancies on what is being imported. I was wondering if you can explain the why this is so- 

a) on basic_environment you have imported agent from microeconomic_system, but not institution. Furthermore, how com environment is importing other parts of the microeconomic system while agent and institution only import themselves from the module?

b) how come environment is the only one of the three microeconomic system components that has imported message_space?

Thanks!
-Maggie

**Comment by skunath** [comment]
Hello,

a) the imports aren't the most clear. Technically you only need imports to support the objects you need. I'll clean up those example files and commit shortly.

b) the message_space class was from a previous experiment. It doesn't need to be there and I'll delete that as well when I commit it.
