### ISSUE TITLE
question on __init___ method

### ISSUE THREAD

**Issue by maggielehr** [gmucsn/mTree#4]
The different components of the microeconomic system are creating different parameters and some of them are less intuitive 

a) in the environment how come agents and institutions are set up as an empty list while in the code for agents and institutions they are input as "None" - how come? In addition does environment need to be entered as a parameter for institution because in our experiment the institution needs to talk to the environment.

b) in the environment what is "goods = [ ]" and what is "out_link = None"

c) in institution what is 'running = False' and what is 'order_book = {}'
what is directory = {} how is that different than boxes?

d) in agent are the "properties" the risk aversion for the agent?

Sorry for the early morning barrage of questions 

-Maggie

**Comment by skunath** [comment]
Hello,

a) The initializations are different. I don't believe there's actually any reason for it and it was a style change thing. I will double check the base class. I'll comment the files to make this clearer. On the second question: yeah. the institution would need to know the environment. Technically, any time they receive a message from the environment we could make the environment address available. You could also add the environment address in the institution initialization. I'll add this to the code and post it.

b) That's stuff from a previous experiment. I'll delete it.

c) That's also from a previous experiment. I'll delete it.

d) The properties are for whatever you'd like to store. You could set that up as you'd like. 

No worries about questions. Makes things clearer to me.
