### ISSUE TITLE
How to make multiple institution?

### ISSUE THREAD

**Issue by MidnightDreamer** [gmucsn/mTree#5]
What are the purposes of the line

container.create_root_environment(BasicEnvironment)
container.setup_environment_institution(BasicInstitution)
container.setup_environment_agents(BasicAgent, 1)? 

I understand that container.setup_environment_agents(BasicAgent, 1) will create one agent in the environment (or however many depending on the arg). However, I tried adding a second argument to the institution (container.setup_environment_institution(BasicInstitution,2)) in an attempt to create a second institution. Yet, this was not possible and threw an error. I was wondering how we can make a second institution and what each of the lines above do.

TIA

**Comment by skunath** [comment]
Hello,

In the container handler you are using I had only intended it to have 1 institution, thus it only gets passed the institution class. I can put some code to show you how to setup additional institutions without the container class. It would be like the other message types we've seen. 

I'll post some example code up for you.

**Comment by MidnightDreamer** [comment]
Thank you!
