### ISSUE TITLE
No module named 'basic_agents'

### ISSUE THREAD

**Issue by maggielehr** [gmucsn/mTree#6]
Although this module was working yesterday I have been unable to make this module work today. my Basic_Agent.py is still functioning, but not basic_environment.py which calls the basic_agent module 

![Uploading basic_agent_error.PNG…]()

**Comment by skunath** [comment]
Hey, I don't think the image you were trying to attach is working. Can you try again?

**Comment by maggielehr** [comment]
Hopefully this one works!

![image](https://user-images.githubusercontent.com/33162945/41620482-d1333482-73d7-11e8-8694-98ab03b450af.png)

**Comment by skunath** [comment]
Oh. I think I see a problem. You are running the the basic_environment file and not the basic_agent_runner.py. I think that suggests that the run configuration for the basic_environment file versus the basic_agent_runner are different. So you might check looking at which file you are running in pycharm.

If that doesn't work, could you send me an email with a copy of the various python files?

**Comment by maggielehr** [comment]
Hi Steven,

The agent_runner which also use that module do not work.

![image](https://user-images.githubusercontent.com/33162945/41622636-33a9bfcc-73de-11e8-832b-346758a9e7b5.png)

The files I am using are directly from the github pull today but I will send you a copy of what I have

-M
